import { EvalSummary, DisputeCase } from '../types/dispute';

export const FALLBACK_EVAL_SUMMARY: EvalSummary = {
  timestamp: '2026-09-01T09:35:38Z',
  total_cases: 100,
  overall_accuracy: 0.90,
  macro_f1: 0.8519,
  precision_contest: 0.80,
  recall_contest: 1.00,
  dispute_prevention_savings_inr: 60000,
  net_financial_gain_inr: 413202.22,
  recovered_amount_inr: 360702.22,
  category_breakdown: {
    fraudulent_unauthorized: {
      category_id: 'fraudulent_unauthorized',
      category_title: 'Fraudulent / Unauthorized Transaction',
      total_cases: 20,
      accuracy: 1.0,
      macro_f1: 1.0,
      net_gain_inr: 107057.33,
    },
    product_service_not_received: {
      category_id: 'product_service_not_received',
      category_title: 'Product or Service Not Received',
      total_cases: 20,
      accuracy: 0.80,
      macro_f1: 0.60,
      net_gain_inr: 74734.48,
    },
    product_unacceptable_defective: {
      category_id: 'product_unacceptable_defective',
      category_title: 'Product Unacceptable, Defective, or Not as Described',
      total_cases: 16,
      accuracy: 1.0,
      macro_f1: 1.0,
      net_gain_inr: 88750.0,
    },
    credit_refund_not_processed: {
      category_id: 'credit_refund_not_processed',
      category_title: 'Credit or Refund Not Processed',
      total_cases: 16,
      accuracy: 0.75,
      macro_f1: 0.5833,
      net_gain_inr: 72902.69,
    },
    duplicate_incorrect_amount: {
      category_id: 'duplicate_incorrect_amount',
      category_title: 'Duplicate Processing or Incorrect Amount',
      total_cases: 14,
      accuracy: 0.8571,
      macro_f1: 0.6190,
      net_gain_inr: 46263.72,
    },
    subscription_recurring_cancellation: {
      category_id: 'subscription_recurring_cancellation',
      category_title: 'Cancelled Subscription / Recurring Charge',
      total_cases: 14,
      accuracy: 1.0,
      macro_f1: 1.0,
      net_gain_inr: 23494.0,
    },
  },
  confusion_matrix: {
    contest_actual_win: 40,
    contest_actual_lose: 0,
    contest_actual_ambiguous: 10,
    accept_actual_win: 0,
    accept_actual_lose: 40,
    accept_actual_ambiguous: 0,
    review_actual_win: 0,
    review_actual_lose: 0,
    review_actual_ambiguous: 10,
  },
  latency: {
    mean_ms: 0.08,
    median_ms: 0.07,
    p95_ms: 0.14,
    min_ms: 0.04,
    max_ms: 0.92,
  },
};
